### ISSUE TITLE
Unable to Deserialize Enum from String

### ISSUE THREAD

**Issue by naftulikay** [softprops/envy#39]
## 🐛 Bug description

When trying to deserialize an untagged enum from a string, deserialization fails.

#### 🤔 Expected Behavior

Having a field `logging_format` which is an enum should deserialize properly from the environment.

#### 👟 Steps to reproduce

```rust
use std::default::Default;

use serde::Deserialize;

#[derive(Debug, Deserialize)]
pub struct Config {
    #[serde(default)]
    pub logging_format: LoggingFormat,
}

#[derive(Debug, Deserialize)]
#[serde(untagged, rename_all = "kebab-case")]
pub enum LoggingFormat {
    Json,
    Plain,
}

impl Default for LoggingFormat {
    fn default() -> Self {
        LoggingFormat::Json
    }
}
```

I'm deserializing this with:

```rust
let config: Config = envy::from_env().unwrap();
```

I'm executing my program with:

```shell
LOGGING_FORMAT=json cargo run
```

And I'm seeing the following output:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("data did not match any variant of untagged enum LoggingFormat")', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/macros.rs:16
   9: <core::result::Result<T, E>>::unwrap
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/result.rs:798
  10: api::main
             at src/main.rs:9
  11: std::rt::lang_start::{{closure}}
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:92
  14: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  15: std::rt::lang_start
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  16: main
```

I have tried variants of the string value of the enum like `JSON`, `json`, `Json`, etc.

#### 🌍 Your environment

 - envy version: 0.4.0
 - Host platform: x86_64-unknown-linux-gnu
 - Target platform: x86_64-unknown-linux-musl
 - Host OS: Ubuntu 18.04 Bionic
 - Rust: 1.33.0

**Comment by naftulikay** [comment]
I refactored a bit:

```rust
use std::default::Default;

use serde::Deserialize;
use serde::Serialize;

#[derive(Debug, Deserialize, Serialize)]
pub struct Config {
    #[serde(default)]
    pub logging_format: LoggingFormat,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum LoggingFormat {
    Json,
    Plain,
}

impl Default for LoggingFormat {
    fn default() -> Self {
        LoggingFormat::Json
    }
}
```

When I serialize the default struct, I see the following, which is what I'd expect:

```json
{"logging_format":"json"}
```

However, even with these changes, it still fails to deserialize:

```
$ LOGGING_FORMAT=json cargo run -q
ERROR: Unable to get configuration from the environment: invalid type: string "json", expected enum LoggingFormat
```

I'm not sure how to proceed.

**Comment by naftulikay** [comment]
I was able to get it working using the following code demonstrated in `lib.rs` in the tests:

```rust
use std::default::Default;

use serde::Deserialize;

#[derive(Debug, Default, Deserialize)]
pub struct Config {
    #[serde(default)]
    pub logging_format: LoggingFormat,
}

#[derive(Debug, Deserialize)]
#[serde(untagged)]
#[serde(field_identifier, rename_all = "kebab-case")]
pub enum LoggingFormat {
    Json,
    Plain,
}

impl Default for LoggingFormat {
    fn default() -> Self {
        LoggingFormat::Json
    }
}
```

I'm not sure what `field_identifier` does, and I can't find it in Serde's documentation, but it does seem to get things working.

**Comment by tobz1000** [comment]
I'd like to suggest re-opening this bug, as the workaround is unsuitable for foreign types (without using remote derive). Ideally, I would be able to deserialise a unit enum from another crate without any extra code.
I also had a quick look at the history of `serde_derive/.../attr.rs`, and it seems like there are no other undocumented attributes.
In my case, I'm deserialising `LevelFilter` from the `log` crate, which has a `serde` implementation which I cannot use.
